# -*- coding: utf-8 -*-
"""İnsatgram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sx0EDTXaCTKfiV-kWzBd2xQEIExI0yn1
"""

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import mean_absolute_error

# y = ax+b

#Veri seti hazırlığı

df = pd.read_csv("instagram.csv", encoding='latin1')

df.head()

"""İsimleri daha kolay kullanayım diye değiştiricem."""

#Veri seti hazırlığı


df.columns=["etki","evde","hashtag","keşfetten","diğer","kaydedilme","yorum","paylaşma","beğenme","profil","takip","başlık","hastags"]

df.head()

y=df[["etki"]]
x=df[["evde","hashtag","keşfetten","diğer","kaydedilme","yorum","paylaşma","beğenme","profil","takip"]]

X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=42)


l=LinearRegression()
model=l.fit(X_train,y_train)#fit()= öğrenmek

model.score(x,y)
r2_skor = model.score(X_test , y_test) #
y_pred = model.predict(X_test) #Modelin daha önceden görmediği değer verir ve bunu y_pred olarak atadım.
mae = mean_absolute_error(y_test, y_pred) #Modelim tahmin ederken ortalama bu kadar hata ile tahmin eder.
print(f"R2 Skoru: {r2_skor}")
print(f"Ortalama hata (MAE): {mae}")

katsayı=model.coef_#xlerin yani targetımızı değiştiren değişkenlerin katsayıları
sabit=model.intercept_#y=ax+b deki b sabit sayısı
print("katsayı:",katsayı)
print("sabit:",sabit)
katsayı.max()

#Verilerin maxı
df["diğer"].max()

#Veri setinin grafik tablosu
plt.figure(figsize=(10, 6))
plt.scatter(y_test, y_pred, color='blue', alpha=0.6)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2) # İdeal tahmin çizgisi
plt.xlabel("Gerçek Etki Değerleri")
plt.ylabel("Tahmin Edilen Etki Değerleri")
plt.title("Gerçek vs Tahmin Karşılaştırması")
plt.savefig("sonuc_grafigi.png")
print("\nGrafik 'sonuc_grafigi.png' olarak kaydedildi.")